[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pine = "59B4m6ZAUAda3pwFJN6Vy7Vf25eZpWtLCEViGXcQ6xXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
